(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const o of n.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&c(o)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const f=document.querySelector(".mobile-menu"),d=document.querySelector(".menu-btn-open"),a=document.querySelector(".menu-btn-close"),u=()=>f.classList.toggle("is-open"),m=()=>document.body.classList.toggle("is-scroll-disabled");d.addEventListener("click",u);a.addEventListener("click",u);d.addEventListener("click",m);a.addEventListener("click",m);document.addEventListener("DOMContentLoaded",()=>{const s=document.documentElement;let t=null;const r=window.matchMedia("(min-width: 320px)");function c(){if(t)return;t=document.createElement("button"),t.className="theme-toggle",t.type="button",t.setAttribute("aria-label","Toggle theme"),t.innerHTML=`
      <div class="icon-wrapper" aria-hidden="true">
        <svg class="icon sun" viewBox="0 0 24 24">
          <path d="M12 4V2m0 20v-2m8-8h2M2 12h2m14.14 5.14l1.42 1.42M4.44 4.44l1.42 1.42m12.28 0l1.42-1.42M4.44 19.56l1.42-1.42M12 6a6 6 0 100 12 6 6 0 000-12z" fill="currentColor"/>
        </svg>
        <svg class="icon moon" viewBox="0 0 24 24">
          <path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z" fill="currentColor"/>
        </svg>
      </div>
    `;const o=localStorage.getItem("theme");if(o)s.setAttribute("data-theme",o);else{const i=window.matchMedia("(prefers-color-scheme: dark)").matches;s.setAttribute("data-theme",i?"dark":"light")}t.addEventListener("click",()=>{const l=s.getAttribute("data-theme")==="dark"?"light":"dark";s.setAttribute("data-theme",l),localStorage.setItem("theme",l)}),document.body.appendChild(t)}function e(){t&&(t.remove(),t=null)}r.matches?c():e();const n=o=>o.matches?c():e();r.addEventListener?r.addEventListener("change",n):r.addListener(n)});
//# sourceMappingURL=index.js.map
